### ISSUE TITLE
`build_rust_binding(root)` not found in this scope

### ISSUE THREAD

**Issue by cedricbeust-okta** [sadikovi/olcPixelGameEngine-rs#1]

**Comment by cedricbeust-okta** [comment]
Oh, looks like it's because I'm building on Windows and this function is only defined for macOS and Linux.

Doesn't this library work on Windows?

**Comment by sadikovi** [comment]
I have not tried building the library on Windows, I don't have access to a Windows machine.

In order to build on Windows, I think you just need to add another function `build_rust_binding` with `#[cfg(target_os = "windows")]` and redefine the function in build.rs. I believe all you may need to provide is Windows paths to the libraries for pthread and such. Hope that helps.

**Comment by davehorner** [comment]
it might help to let people know windows doesn't work on your readme.  I did add the function and I'm left with the linker error; not sure where to go from there.

`error: could not find native static library `olcRustBindingApp`, perhaps an -L flag is missing?
error: could not compile `olc_pixel_game_engine` due to previous error`

**Comment by JonnyB247** [comment]
Thanks for the hint, sadikovi. I added a pull request with the Windows version of `build_rust_binding`.

**Comment by jacobguilbeau** [comment]
Can a new crate version be issued with these windows changes?  Last version 0.5.0 doesn't contain this change.

**Comment by sadikovi** [comment]
I just published the new version (https://crates.io/crates/olc_pixel_game_engine/0.6.0).
